### ISSUE TITLE
when step in  Next process, if router to other path , the userGuide--message Modal  won't disappear 

### ISSUE THREAD

**Issue by ChenYCL** [sandeshshrestha/react-user-guide#14]
hello,i guess it's a problem,when i in next process, if i  do nothting and change route . the pop-up modal remains.

now my solutions is remove the dom to remove.
```
componentWillUnmount() {
    const dom = document.getElementsByClassName('userGuide--mask');
    if (dom.length) {
      dom[0].remove();
    }
  }
```
need a  destory event or auto destory

**Comment by sandeshshrestha** [comment]
@ChenYCL Thanks for this.
